

- name: Java - Create a directory
  action: file path=/{{java_root}} state=directory recurse=yes

- name: Java - Check if path exists
  stat: path={{java_root}}/{{ java_version_folder }}
  register: check_java_installed

- name: Java - Download java tar ball
  get_url: url="{{java_url_root}}/{{java_url_filename}}"
           dest="{{java_root}}/{{java_url_filename}}"
           sha256sum={{java_url_filename_sha256}}
  when: check_java_installed.stat.exists == false

- name: Java - Unarchive java tar ball
  shell: tar -zxf  "{{java_root}}/{{java_url_filename}}" -C "{{java_root}}"
  when: check_java_installed.stat.exists == false

- name: Java - Check if path exists
  stat: path={{java_root}}/{{ java_version_folder }}
  register: check_java_installed

- name: Java - Create link
  file: src={{java_root}}/{{java_version_folder}} dest={{java_home}} state=link 

- name: Java - Configure JAVA_HOME for root
  action: lineinfile dest=/root/.bash_profile line="JAVA_HOME={{java_home}}"

- name: Java - Configure PATH for root
  action: lineinfile dest=/root/.bash_profile line="PATH=$PATH:$JAVA_HOME/bin"

