---

    config.vm.define 'machine2' do |machine|
      machine.vm.hostname = 'machine2'
      machine.vm.network "private_network", ip: "192.168.77.22"
    end

    config.vm.define 'machine1' do |machine|
      machine.vm.hostname = 'machine1'
      machine.vm.network "private_network", ip: "192.168.77.21"

      machine.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yml"

        # Disable default limit (required with Vagrant 1.5+)
        ansible.limit = 'all'
      end
    end